package(default_visibility = ["//visibility:__pkg__"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "bundled",
    srcs = [
        "app.js",
        "index.html",
    ],
    visibility = [
        "//visibility:public",
    ],
)
